# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-20 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='', upload_to='imgs'),
            preserve_default=False,
        ),
    ]
